"""add role column to users

Revision ID: d9ce52419b88
Revises: 1a78ae910382
Create Date: 2026-06-09 12:00:24.868608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9ce52419b88'
down_revision: Union[str, Sequence[str], None] = '1a78ae910382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_trade_no'), table_name='orders')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_call_logs_created_at'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_id'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_request_id'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_status_code'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_user_id'), table_name='call_logs')
    op.drop_table('call_logs')
    # ### end Alembic commands ###
    op.add_column('users', sa.Column('role', sa.Enum('user', 'admin', name='userrole'), server_default='user', nullable=False))

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('api_key_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('input_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('output_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cost_cents', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], name=op.f('call_logs_api_key_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('call_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('call_logs_pkey'))
    )
    op.create_index(op.f('ix_call_logs_user_id'), 'call_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_call_logs_status_code'), 'call_logs', ['status_code'], unique=False)
    op.create_index(op.f('ix_call_logs_request_id'), 'call_logs', ['request_id'], unique=True)
    op.create_index(op.f('ix_call_logs_id'), 'call_logs', ['id'], unique=False)
    op.create_index(op.f('ix_call_logs_created_at'), 'call_logs', ['created_at'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('key_value', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('base_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('total_calls', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('disabled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('api_keys_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('api_keys_pkey'))
    )
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount_cents', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'PAID', 'CANCELLED', 'EXPIRED', name='orderstatus'), autoincrement=False, nullable=False),
    sa.Column('trade_no', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('orders_plan_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('orders_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('orders_pkey'))
    )
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_index(op.f('ix_orders_trade_no'), 'orders', ['trade_no'], unique=True)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    # ### end Alembic commands ###
    op.drop_column('users', 'role')