"""add call_logs table

Revision ID: ecaebb06b2df
Revises: 5e030b585a69
Create Date: 2026-06-07 21:37:07.215599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecaebb06b2df'
down_revision: Union[str, Sequence[str], None] = '5e030b585a69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('call_logs', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('call_logs', 'input_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('call_logs', 'output_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('call_logs', 'total_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('call_logs', 'status_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('call_logs', 'duration_ms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('call_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_call_logs_created_at'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_request_id'), table_name='call_logs')
    op.create_index(op.f('ix_call_logs_api_key_id'), 'call_logs', ['api_key_id'], unique=False)
    op.create_unique_constraint(None, 'call_logs', ['request_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'call_logs', type_='unique')
    op.drop_index(op.f('ix_call_logs_api_key_id'), table_name='call_logs')
    op.create_index(op.f('ix_call_logs_request_id'), 'call_logs', ['request_id'], unique=True)
    op.create_index(op.f('ix_call_logs_created_at'), 'call_logs', ['created_at'], unique=False)
    op.alter_column('call_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('call_logs', 'duration_ms',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('call_logs', 'status_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('call_logs', 'total_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('call_logs', 'output_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('call_logs', 'input_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('call_logs', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
