"""add quota fields to users

Revision ID: f0ce828cb880
Revises: ecaebb06b2df
Create Date: 2026-06-08 15:36:16.086850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0ce828cb880'
down_revision: Union[str, Sequence[str], None] = 'ecaebb06b2df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ========== 1. 一次性添加所有新列（允许为空） ==========
    op.add_column('users', sa.Column('plan', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('quota_limit', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('quota_used', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('extra_tokens', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('subscription_expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ========== 2. 为现有行填充合理的默认值 ==========
    op.execute("UPDATE users SET plan = 'free' WHERE plan IS NULL")
    op.execute("UPDATE users SET quota_limit = 1000 WHERE quota_limit IS NULL")   # 免费套餐默认额度
    op.execute("UPDATE users SET quota_used = 0 WHERE quota_used IS NULL")
    op.execute("UPDATE users SET extra_tokens = 0 WHERE extra_tokens IS NULL")
    # 日期字段：created_at/updated_at 设为当前时间（注意：sqlite 和 postgres 语法可能不同）
    # 这里使用一个通用的写法，假设数据库是 postgresql
    op.execute("UPDATE users SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE users SET updated_at = NOW() WHERE updated_at IS NULL")
    # subscription_expires_at 可以保持 NULL，表示永不过期

    # ========== 3. 将所有应非空的列改为 NOT NULL ==========
    op.alter_column('users', 'plan', nullable=False)
    op.alter_column('users', 'quota_limit', nullable=False)
    op.alter_column('users', 'quota_used', nullable=False)
    op.alter_column('users', 'extra_tokens', nullable=False)
    op.alter_column('users', 'created_at', nullable=False)
    op.alter_column('users', 'updated_at', nullable=False)
    # subscription_expires_at 保留可空，不需要 alter

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'subscription_expires_at')
    op.drop_column('users', 'extra_tokens')
    op.drop_column('users', 'quota_used')
    op.drop_column('users', 'quota_limit')
    op.drop_column('users', 'plan')
    # ### end Alembic commands ###
